#!/usr/bin/env bash
# Download and unpack vendor C libraries needed to build the Wasm engine.
# Run automatically by build.sh, or manually: bash engine/vendor-download.sh
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p vendor

SENTINEL=vendor/.vendor-ready
[ -f "$SENTINEL" ] && exit 0

fetch() {
  local name=$1 url=$2
  [ -d "vendor/$name" ] && return
  echo "  → $name"
  local tmp; tmp=$(mktemp -d)
  curl -fsSL "$url" | tar -xz -C "$tmp"
  local extracted; extracted=$(ls "$tmp" | head -1)
  mv "$tmp/$extracted" "vendor/$name"
  rm -rf "$tmp"
}

fetch_file() {
  local dest=$1 url=$2
  [ -f "vendor/$dest" ] && return
  echo "  → $dest"
  curl -fsSL "$url" -o "vendor/$dest"
}

echo "Fetching vendor libraries..."
fetch libdeflate-1.22 https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.22.tar.gz
fetch lz4-1.10.0      https://github.com/lz4/lz4/archive/refs/tags/v1.10.0.tar.gz
fetch zstd-1.5.6      https://github.com/facebook/zstd/archive/refs/tags/v1.5.6.tar.gz
fetch brotli-1.1.0    https://github.com/google/brotli/archive/refs/tags/v1.1.0.tar.gz
fetch snappy-1.2.1    https://github.com/google/snappy/archive/refs/tags/1.2.1.tar.gz
# snappy-stubs-public.h is normally generated by CMake; provide a Wasm-safe version.
if [ ! -f vendor/snappy-1.2.1/snappy-stubs-public.h ]; then
  cat > vendor/snappy-1.2.1/snappy-stubs-public.h <<'EOF'
#ifndef THIRD_PARTY_SNAPPY_OPENSOURCE_SNAPPY_STUBS_PUBLIC_H_
#define THIRD_PARTY_SNAPPY_OPENSOURCE_SNAPPY_STUBS_PUBLIC_H_
#include <stddef.h>
#include <stdint.h>
#include <sys/uio.h>
#define SNAPPY_HAVE_SYS_UIO_H 1
#define SNAPPY_HAVE_SSSE3 0
#define SNAPPY_HAVE_BMI2 0
#define SNAPPY_HAVE_X86_CRC32 0
#define SNAPPY_HAVE_NEON_CRC32 0
#endif
EOF
fi
fetch bzip2-1.0.8 https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
fetch_file qoi.h  https://raw.githubusercontent.com/phoboslab/qoi/master/qoi.h

# LZMA SDK — extract only the C/ subdirectory; discard Java/C#/CPP/Asm.
# jljusten/LZMA-SDK master is pinned at 18.05 (2018, unmaintained mirror).
if [ ! -d vendor/lzma-sdk ]; then
  echo "  → lzma-sdk"
  lzma_tmp=$(mktemp -d)
  curl -fsSL https://github.com/jljusten/LZMA-SDK/archive/refs/heads/master.tar.gz \
    | tar -xz -C "$lzma_tmp"
  mv "$lzma_tmp"/LZMA-SDK-master/C vendor/lzma-sdk
  rm -rf "$lzma_tmp"
fi

touch "$SENTINEL"
echo "Done."
